GET http://localhost:3000/moneyUpdates

###

GET http://localhost:3000/moneyUpdates/622c00c6738cd7ea8ba721e0

###
POST http://localhost:3000/moneyUpdates
Content-Type: application/json

{
    "targetYear": 2080,
    "targetGoal": 1000000,
    "withdrawalRate": 40000,
    "interestRate": 7,
    "annualIncome": 80000,
    "annualExpense": 50000,
    "username": "622c147ff06267c78ef9041f"
}

###

DELETE http://localhost:3000/moneyUpdates/622c1493f06267c78ef90421

###

PATCH http://localhost:3000/moneyUpdates/YOUR_ID_HERE
Content-Type: application/json

{
    "targetYear": 2070
}