GET http://localhost:3000/users

###

GET http://localhost:3000/users/62297321b585b6e544fe79d2

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "kamal",
    "accountBalance": 5000,
    "age": 18   
}

###

DELETE http://localhost:3000/users/622c1409d522800736298837

###

PATCH http://localhost:3000/users/62297321b585b6e544fe79d2
Content-Type: application/json

{
    "age": 96
}