GET http://localhost:3000/moneyUpdates

###

GET http://localhost:3000/moneyUpdates/YOUR_ID_HERE

###
POST http://localhost:3000/moneyUpdates
Content-Type: application/json

{
    "targetYear": 2080,
    "targetGoal": 1000000,
    "withdrawalRate": 40000,
    "interestRate": 7,
    "annualIncome": 80000,
    "annualExpense": 50000
}

###

DELETE http://localhost:3000/moneyUpdates/YOUR_ID_HERE

###

PATCH http://localhost:3000/moneyUpdates/YOUR_ID_HERE
Content-Type: application/json

{
    "targetYear": 2070
}