GET http://localhost:3000/fireup

###

GET http://localhost:3000/fireup/620f42f1ebb959dc3c57eded

###
POST http://localhost:3000/fireup
Content-Type: application/json

{
    "name": "Test User",
    "age": 19,
    "accountBalance": 1000,
    "email": "test@acm.com",
    "password": "password"
}

###

DELETE http://localhost:3000/fireup/620f413416444a1efafb9bb9

###

PATCH http://localhost:3000/fireup/621534c21d3db19f9db23fa5
Content-Type: application/json

{
    "name": "New Jana"
}