GET http://localhost:3000/fireup

###

GET http://localhost:3000/fireup/621534c21d3db19f9db23fa5

###
POST http://localhost:3000/fireup
Content-Type: application/json

{
    "name": "Naveen",
    "age": 18,
    "accountBalance": 5000
}

###

DELETE http://localhost:3000/fireup/6216fde1fc93b62560ca0e01

###

PATCH http://localhost:3000/fireup/621534c21d3db19f9db23fa5
Content-Type: application/json

{
    "age": 96
}