GET http://localhost:3000/money

###

GET http://localhost:3000/moneyUpdates/622c00c6738cd7ea8ba721e0

###
POST http://localhost:3000/moneyUpdates
Content-Type: application/json

{
    "User": "624741a2c2343ffdd0c20589",
    "targetAge": 65,
    "annualIncome": 200000,
    "annualExpense": 100000,
    "initStocks": 80000,
    "initBonds": 50000,
    "initCash": 100000
}

###

DELETE http://localhost:3000/moneyUpdates/622c1493f06267c78ef90421

###

PATCH http://localhost:3000/moneyUpdates/YOUR_ID_HERE
Content-Type: application/json

{
    "targetYear": 2070
}